### ISSUE TITLE
implement realign and unwarp with fieldmaps

### ISSUE THREAD

**Issue by Remi-Gau** [cpp-lln-lab/CPP_BIDS_SPM_pipeline#104]
- [ ] convert field maps with bidsme --> added to general Kanban

see:
-  https://github.com/cpp-lln-lab/CPP_BIDS_SPM_pipeline/issues/83#issue-702783256

**Comment by Remi-Gau** [comment]
I am starting to work on this.

Creating a function to first deal with realign and unwarp. 
Realizing that a LOT of the code for realign, realign and reslice, realign and unwarp is almost the same. So I will do some refactoring right after that.

**Comment by CerenB** [comment]
heya! @Remi-Gau and @marcobarilari ok, I see a bit better now. Would you like to share your batch.m script with me? So I can see an example of which data you are using with realign + unwrapping? Is this option only for field map (realign + unwrap) unlike the rest of the func images with realign + reslice ?

**Comment by Remi-Gau** [comment]
Hey @CerenB 

Actually you can totally use realign and unwarp for "mini tesla" (<-- I freaking love this #MakeFmriCuteAgain)

Right now we have not used it yet.

But I could update some of the batches in the demo folder to show how it's used. Would that be OK?

**Comment by Remi-Gau** [comment]
And realign and unwarp can function in 2 ways:
- by itself
- or with a voxel displacement map (vdm) for each run.

The vdm is created from the fieldmap: I have not yet created the batches to create those. That's next on my to do list. :-)

So you can already use realign and unwarp but the batch can't make use of your fieldmap yet. :-)

**Comment by CerenB** [comment]
sorry to be ignorant with these.. feel free to say "go and read". 
How about if I have the mini runs (20s) with reverse phase-encoding? would I use the same batch (realign and unwrap) or it would be different analysis?

**Comment by Remi-Gau** [comment]
well I learned the hard way that there is no good documentation on using vdm with spm...

some important details are like one like in the spm manual lost in a sea of other stuff... 

so there is no easy "go and read"

for the reverse-phase encoding approach, I think this will require using FSL... So we are going to need to mix things up a bit.

it was all too boring so far...

**Comment by CerenB** [comment]
Thank you for confirming that I should use FSL for reverse encoding acquisition. Because I heard about it and thought oh for sure spm has equivalent...
