### ISSUE TITLE
smoothing batch looking for ra prefix

### ISSUE THREAD

**Issue by CerenB** [cpp-lln-lab/CPP_BIDS_SPM_pipeline#107]
I've ran STC and SpatialPrep scripts, now it's time for some smoothing. But it crashes saying:

```
Error using inputFileValidation (line 12)
This file does not exist:
/Users/battal/Cerens_files/fMRI/Processed/RhythmCateg/BlockDesign/derivatives/SPM12_CPPL/sub-001/ses-001/func/rasub-001_ses-001_task-RhythmCategBlock_run-001_bold.nii[.gz]

Error in setBatchSmoothing (line 34)
            files =
            inputFileValidation(subFuncDataDir,
            prefix, fileName);

Error in bidsSmoothing (line 29)
            matlabbatch =
            setBatchSmoothing(BIDS, opt,
            subID, funcFWHM);

Error in rhythmCategBlock (line 27)
bidsSmoothing(FWHM, opt);
```
 

When I look at `getPrefix` function, not much going on for STC (meaning in my folder, it does not create "a" prefixed .nii files) but then this function has a subfunc prefixforSTC, which seems to be creating "ra" prefix for smoothing batch both for anatomical and functional images:
```
       case 'STC'

        case 'preprocess'
            prefix = prefixForSTC(prefix, opt);

            % when smoothing is done on non-normalized data (in the space of T1w)
        case 'smoothing_space-T1w'
            prefix = prefixForSTC(prefix, opt);
            prefix = [spm_get_defaults('realign.write.prefix') prefix];

        case 'smoothing'
            prefix = prefixForSTC(prefix, opt);
            prefix = [spm_get_defaults('normalise.write.prefix') prefix];
```

Am I doing something wrong?

**Comment by Remi-Gau** [comment]
Nope I think I must have tweaked something when working on the high-res and now we have this issue... That's why I need MORE tests... Sigh...

**Comment by CerenB** [comment]
oh no... but maybe I can/should go back in some branches... I thought I did not step on high-res branch but i will check!

**Comment by Remi-Gau** [comment]
Do you have this in your getOption:
```
opt.space = 'MNI';
```

**Comment by CerenB** [comment]
No!

**Comment by CerenB** [comment]
it is working - well doing some smoothing
