### ISSUE TITLE
find a way to specify the contrasts to compute

### ISSUE THREAD

**Issue by Remi-Gau** [cpp-lln-lab/CPP_BIDS_SPM_pipeline#11]
It will make most sense to rely on the BIDS extension on stats models.

Will go through it again and try to come up with some options.

https://docs.google.com/document/d/1bq5eNDHTb6Nkx3WUiOBgKvLNnaa5OMcGtD0AZ9yms2M/edit?usp=sharing

**Comment by Remi-Gau** [comment]
OK here is what I found: https://fitlins.readthedocs.io/en/latest/model.html

This comes from the Poldrack lab who is mostly behind the BIDS stats models extension.

They have a model json file that describes:
- out to prepare the regressors for the GLM: `Transformation`
- the design matrix: `X`
- the contrasts to compute: `contrasts`

It also allows to specify those for different levels of the analysis:
- run
- session
- subject
- dataset

There are examples here: https://fitlins.readthedocs.io/en/latest/examples/models.html

In our case I guess that for now we want to concentrate on the contrasts part. So it could look something like that.

```json
{
  "Name": "Basic",
  "Description": "",
  "Input": {
    "task": "motionloc"
  },
  "Steps": [
    {
      "Level": "subject",
      "AutoContrasts": ["stim_type.motion", "stim_type.static"],
      "Contrasts": [
        {
          "Name": "motion_vs_static",
          "ConditionList": [
            "stim_type.motion",
            "stim_type.static"
          ],
          "weights": [1, -1],
          "type": "t"
        }
      ]
    },
    {
      "Level": "dataset",
      "AutoContrasts": ["stim_type.motion", "stim_type.static", "motion_vs_static"]
    }
  ]
}
```
In brief this means:
- at the subject level automatically compute the t contrast against baseline for the condition `motion`and `static` and compute the t-contrats for motion VS static with these given weights.
- at the level of the data set (so RFX) do the t contrast of the `motion`, `static`, `motion VS static`.

What do you think @mohmdrezk ?

**Comment by mohmdrezk** [comment]
Looks interesting. 
Will have a look at it.

**Comment by Remi-Gau** [comment]
Will start working on that one.

**Comment by Remi-Gau** [comment]
@mohmdrezk I have a working version of that for the visMotion_V2 data set.

You can check it on the my `contrast-specification` branch. If this sort of works for you I can send a PR.

**Comment by Remi-Gau** [comment]
Oh actually this only works for the FFX. Let me try to make it work for the RFX too.

**Comment by Remi-Gau** [comment]
OK RFX is done too.

You can check my branch or I can send a PR.

**Comment by mohmdrezk** [comment]
Will check it now.

**Comment by mohmdrezk** [comment]
I don’t know if I did correctly or if you got an update. 

1 - I updated the the function pmCon 
And changed the 
model.Steps(iStep).Level. —> model.Steps{iStep}.Level

Because I was getting the following error 



Now it's working after the change. 

2- one minor suggestion about the naming of the RFX folders. I know its silly but we should change the trial_type name.VisMot —> VisMot. 



3- Github question: 
What was the right way to send you a pull request? 
I can’t send a pull request since I was on your repo. 
I also cant clone your repo and update it with a pull reuqest to you.
So what was the better steps?

Thanks

**Comment by Remi-Gau** [comment]
> 2- one minor suggestion about the naming of the RFX folders. I know its silly but we should change the trial_type name.VisMot —> VisMot. 

Did we fix that?

**Comment by mohmdrezk** [comment]
Not to my knowledge. So No.

**Comment by Remi-Gau** [comment]
> Not to my knowledge. So No.
Fixed that in one of the commit I pushed on your branch to fix pmCon

**Comment by Remi-Gau** [comment]
This is more of a reminder to go and check the BIDS spec and how this solved by fitlins.

Say you have the following model file: 
 
{
  "Name": "Basic",
  "Description": "",
  "Input": {
    "task": "motionloc"
  },
  "Steps": [
    {
      "Level": "run",
      "AutoContrasts": ["stim_type.motion", "stim_type.static"],
    },
    {
      "Level": "subject",
      "AutoContrasts": ["stim_type.motion", "stim_type.static"],
    },
    {
      "Level": "dataset",
      "AutoContrasts": [ "stim_type.static"]
    }
  ]
}

The way we have coded this is that the group (dataset) level would take the contrasts generated at the subject level by autocontrast at the subject level but if the model also has a run level with autocontrast then there is potential ambiguity.

PS: not an issue for us at the moment but I want to make sure that we are using the BIDS data model correctly to prevent headaches in the future.
