### ISSUE TITLE
Update model json of demos folder so they all include a "design matrix" specification

### ISSUE THREAD

**Issue by CerenB** [cpp-lln-lab/CPP_BIDS_SPM_pipeline#111]
sorry it's not `bidsffx.m` file but in line 50 of `fullpathOnsetFileName = convertOnsetTsvToMat(opt, tsvFile, isMVPA)`

`isTrialType = strfind(model.Steps{runIdx}.Model.X, 'trial_type.');`
But in the visMotion model (that I took as template), we do not have `.Model.X` so it's crashing

the usage of `Model.X` continues in the following parts, so I'm wondering if I should change my model, then or replace `Model.X `with `AutoContrasts`?

**Comment by CerenB** [comment]
oh accordi ng to this: https://github.com/cpp-lln-lab/CPP_BIDS_SPM_pipeline/blob/master/demo/model-MoAE_smdl.json

it wants Model.X which are the 6 motion parameter dimensions. Ok, I'll add them up!

**Comment by Remi-Gau** [comment]
You should update your model json to make sure it includs an `X`.

I have not got around to update all the models json in the demo folder... Sorry.

The "only" valid one ATM is the one for MoAE: https://github.com/cpp-lln-lab/CPP_BIDS_SPM_pipeline/blob/dev/demos/MoAE/models/model-MoAE_smdl.json

**Comment by Remi-Gau** [comment]
For now, the pipeline will ALWAYS include the motion regressor, whether you include them in X or not. 

This should NOT be the final behavior of the pipeline : on our TODO list.

**Comment by Remi-Gau** [comment]
Will rename this issue so we know we have to update the model json.
