### ISSUE TITLE
saving spatial preprocessing spm graphs/ figures

### ISSUE THREAD

**Issue by CerenB** [cpp-lln-lab/CPP_BIDS_SPM_pipeline#113]
would it be interesting to save normalised mutual information coregistration + image realignment graphs/figures?

**Comment by Remi-Gau** [comment]
YES !! That will work on matlab: we need need to make sure that we open a figure and things should be displayed there. 
Need to curate to then make sure where things are saved: something better curated than the `spm_today's-date.ps` than SPM does by default.

On octave: that will be a no go I think the lack of support for a "GUI" in octave.

**Comment by CerenB** [comment]
@Remi-Gau  and @marcobarilari FYI, even if the `src` folder is clean from previous `.ps` files, still the `bidsSpatialPrepro` function crashes here due to `copyGraphWindowOutput` function:


```
SPM12: spm_imcalc (v6961)                          22:26:47 - 10/11/2020
========================================================================
ImCalc Image: /Users/battal/Cerens_files/fMRI/Processed/RhythmCateg/Pilots/RhythmFT/derivatives/cpp_spm/sub-001/ses-001/anat/msub-001_ses-001_T1w_mask.nii
10-Nov-2020 22:26:48 - Done    'Image Calculator'
10-Nov-2020 22:26:48 - Done

Error using movefile
All arguments must be character vectors.

Error in copyGraphWindownOutput (line 54)
      movefile( ...

Error in copyFigures (line 20)
  imgNb = copyGraphWindownOutput(opt, subID, 'realign');

Error in bidsSpatialPrepro (line 101)
      copyFigures(BIDS, opt, subID);

Error in RhythmFT_run (line 29)
  bidsSpatialPrepro(opt);
```

**Comment by Remi-Gau** [comment]
Hum... Some bugs just don't want to die.

Can you tell me what's in the folder of `RhythmFT_run` at the moment of the crash?
