### ISSUE TITLE
create a function that copies the raw data into a derivatives/SPM12-CPP directory

### ISSUE THREAD

**Issue by Remi-Gau** [cpp-lln-lab/CPP_BIDS_SPM_pipeline#25]
@marcobarilari I am assigning you to this but feel to tell me to take a hike. ;-p

**Comment by Remi-Gau** [comment]
do you think we can have this ready before the workshop? 

Just to know if this issue should be included in our first milestone?

**Comment by marcobarilari** [comment]
It should not be difficult, I'll work on it tomorrow/wednesday and let you know if it can be ready asap. LMK if it would work this way.

**Comment by Remi-Gau** [comment]
Okidoki. Send a PR when it is ready to test then I suspect that me and @mohmdrezk will double check it.
