### ISSUE TITLE
Consider to unzip the bold files in a separate function from BIDS_rmDumies.m

### ISSUE THREAD

**Issue by marcobarilari** [cpp-lln-lab/CPP_BIDS_SPM_pipeline#26]
Create a function to run before the dummies removing, might also work smoother if `opt.numDummies = ` set to 0.

**Comment by Remi-Gau** [comment]
I guess this is related to issue #25

**Comment by Remi-Gau** [comment]
do you think we can have this ready before the workshop?

Just to know if this issue should be included in our first milestone?

**Comment by mohmdrezk** [comment]
Yes, it will be ready before. 
But it shouldnt be a problem for the workshop since the data will be in bids format ready for the preprocessing directly.

**Comment by Remi-Gau** [comment]
Awesome. I just would be very happy if we can have a version 0.0.1 of the pipeline ready for the workshop. :-)
