### ISSUE TITLE
accommodate preprocessing for MVPA usecase

### ISSUE THREAD

**Issue by Remi-Gau** [cpp-lln-lab/CPP_BIDS_SPM_pipeline#41]
For MVPA we do not want to use the normalized images, but we might still want to run a GLM to use the beta images as features for our MVPA.

The problem is that currently the images are not resliced after realignement and the FFX script will throw an error when SPM runs check_orientation on the input images and realizes there are not in the same space.

We simply need to reslice the images after realignement is done (or run realign: estimate and reslice instead).

**Comment by Remi-Gau** [comment]
@mohmdrezk see the related comment on the PR I sent to your pmCon branch.

I will take care of fixing that.

**Comment by Remi-Gau** [comment]
See if there is a cleaner way to handle this (possibly via BIDS model) rather than having to carry the `isMVPA` flag everywhere !

**Comment by mohmdrezk** [comment]
Everything in the prepossessing pipeline is identical until the ffx point where the model is called. 
A proposal:
- We remove the isMVPA from all the functions.
- in the FFX function, if model filename has 'Multivariate' or 'MVPA' then we will know that it is a multi-variate model
- The mvpaSuffix would be replaced by a fileSuffix (sounds more general) 
` mvpaSuffix = setMvpaSuffix(isMVPA);` 

 Inside the new fileSuffix function, if the model has the 'Multivariate' or 'MVPA' in the filename it will add the MVPA suffix
and the isMVPA is out from all scripts. 
What do you think?

**Comment by Remi-Gau** [comment]
I think you read my mind !!!! :smile:
