### ISSUE TITLE
[WORKSHOP 2019] - MVPA

### ISSUE THREAD

**Issue by Remi-Gau** [cpp-lln-lab/CPP_BIDS_SPM_pipeline#47]
Are we planning to have some basic MVPA analysis ready to run or just prepare the data for MVPA?

**Comment by mohmdrezk** [comment]
not clear yet, but even if we do something related to MVPA, the data will be ready, and it will be a demonstration. If we present something related to MVPA, I will have the data ready for demonstration.

**Comment by mohmdrezk** [comment]
we will discuss soon what will be presented.

**Comment by Remi-Gau** [comment]
OK. just using issues here to keep track of things

**Comment by Remi-Gau** [comment]
Reopened here: https://github.com/cpp-lln-lab/fMRI_workshop_201911/issues/4
