### ISSUE TITLE
spm_jsonread issue

### ISSUE THREAD

**Issue by mohmdrezk** [cpp-lln-lab/CPP_BIDS_SPM_pipeline#54]
I am testing the scripts but I am having an issue I cant get around. the 2 json files for the univariate and multivariate are read differently and give different output structure. 

When I use the json read, one of them gives "model.Steps" as 2x1 structure , and the other as 2x1 cell. 

@Remi-Gau : Can you try loading the 2 json files and see if you can figure out what is the mistake in one of them. What should I change in the json file in order to have the same kind of output? 

This throws an error when I am running the contrasts "pmCon" because in pmCon:
Step = model.Steps{iStep};
or 
Step = model.Steps(iStep);

So the 2 models should give the same output. Do you have an idea on how to fix this?

![Screenshot 2019-11-02 at 15 19 58](https://user-images.githubusercontent.com/9597815/68072278-5d0aa580-fd84-11e9-965f-f16877cd2340.png)

[jsonFiles.zip](https://github.com/cpp-lln-lab/CPP_BIDS_SPM_pipeline/files/3800563/jsonFiles.zip)

**Comment by Remi-Gau** [comment]
Ha I thought I had fixed that. It seems to be related to the way spm_jsonreads decide to output things: Only work around I found was to add a dummy empty dataset field:

```json
{
  "Name": "Motion Decoding",
  "Description": "contrasts for the motion localizer dataset",
  "Input": {
    "task": "motionDecoding"
  },
  "Steps": [
    {
      "Level": "run",
      "AutoContrasts": ["trial_type.Vis_U", "trial_type.Vis_D", "trial_type.Vis_R", "trial_type.Vis_L","trial_type.Aud_U", "trial_type.Aud_D", "trial_type.Aud_R", "trial_type.Aud_L"]
    },
    {
      "Level": "dataset",
      "AutoContrasts": []
    }
  ]
}
```

I have just pushed a couple of commits to include that.

**Comment by mohmdrezk** [comment]
I already had the dataset field but it didn’t work. But following your logic, I added the subject field (that was missing) and now it works.

**Comment by mohmdrezk** [comment]
Now everything is working. I did the updates and changed very few things and sent you a pull request.
