### ISSUE TITLE
reslicing in the realignment batch (JOBS vs data)

### ISSUE THREAD

**Issue by mohmdrezk** [cpp-lln-lab/CPP_BIDS_SPM_pipeline#57]
The saved jobs in the realignment step indicates that reslicing occurs to the mean image and all the images. 

<img width="914" alt="Screenshot 2019-11-25 at 18 46 58" src="https://user-images.githubusercontent.com/9597815/69565713-d5483d80-0fb5-11ea-9c3a-fa8af1335a90.png">

However when we look at the output derivatives folder no reslicing is performed to the mean nor the individual images. 

Issues to be fixed:
1- we want to reslice the mean image only and have the output "rmeana*.nii" in the derivatives directory.
2- The saved JOB matchs the output files.

**Comment by Remi-Gau** [comment]
It seems that the current spm_my_defaults  with `defaults.realign.write.which = [0 1];` now does the trick.

The batch only shows 'Mean only' and it outputs the `mean*.nii`. 

I don't think that realignement can ever output a "rmean*.nii", right? The reslicing creates the mean image, we don't reslice it twice?

**Comment by mohmdrezk** [comment]
You are correct. 
The mean is resliced and we dont need to re-slice it again.

**Comment by Remi-Gau** [comment]
OK cool
closing this then
