### ISSUE TITLE
getData :Accommidate scripts for structural analysis (without funtional).

### ISSUE THREAD

**Issue by mohmdrezk** [cpp-lln-lab/CPP_BIDS_SPM_pipeline#68]
[group, opt, BIDS] = getData(opt) 

% get metadata for bold runs for that task
% we take those from the first run of the first subject assuming it can
% apply to all others.
metadata = spm_BIDS(BIDS, 'metadata', ...
    'task', opt.taskName, ...
    'sub', subjects{1}, ...
    'type', 'bold');
if iscell(metadata)
    opt.metadata = metadata{1};
else
    opt.metadata = metadata;
end

Metadata looks for functional data and throws an error if only looking at structural data.

**Comment by Remi-Gau** [comment]
maybe the best way to handle this is to add an argin parameter to say what ´type´ we want the metadata of and make ´bold´ the default. 

how does that sound?

**Comment by mohmdrezk** [comment]
Sounds perfect
