### ISSUE TITLE
refactor doc and implement jupyter notebook

### ISSUE THREAD

**Issue by Remi-Gau** [cpp-lln-lab/CPP_BIDS_SPM_pipeline#78]

**Comment by CerenB** [comment]
@Remi-Gau @mohmdrezk In the documentation it says _"at the subject level automatically compute the t contrast against baseline for the condition motion and static and compute the t-contrats for motion VS static with these given weights."_

So I do not need to add `motion` and `static` conditions with the `weight = 1` to check these against baseline? 

`An example of json file could look something like that.`

```
{
  "Name": "Basic",
  "Description": "",
  "Input": {
    "task": "motionloc"
  },
  "Steps": [
    {
      "Level": "subject",
      "AutoContrasts": ["stim_type.motion", "stim_type.static"],
      "Contrasts": [
        {
          "Name": "motion_vs_static",
          "ConditionList": [
            "stim_type.motion",
            "stim_type.static"
          ],
          "weights": [1, -1],
          "type": "t"
        }
      ]
    },
    {
      "Level": "dataset",
      "AutoContrasts": ["stim_type.motion", "stim_type.static", "motion_vs_static"]
    }
  ]
}
```

**Comment by Remi-Gau** [comment]
That's correct: for anything entered as an auto-contrast the weights will be set automatically.

Though you can still specify it manually if you prefer.

In general though make sure that everything looks fine wrt contrats weights when vizualizing the results : I have written some test to make sure it does what we want it to do but I have not tried all the "edge cases"

**Comment by Remi-Gau** [comment]
@CerenB can I close this?

**Comment by CerenB** [comment]
sure!
