### ISSUE TITLE
refactor getRuns, getSessions, getFilenames

### ISSUE THREAD

**Issue by Remi-Gau** [cpp-lln-lab/CPP_BIDS_SPM_pipeline#9]
As pointed out by @mohmdrezk these functions can be refactored into one.

**Comment by Remi-Gau** [comment]
@marcobarilari @anege do you want to give this a try?

**Comment by marcobarilari** [comment]
Sure!

**Comment by anege** [comment]
I will do it, please give me some more time to test! cause apparently I was working in the wrong branch
