### ISSUE TITLE
bidsCopyRawFolder function

### ISSUE THREAD

**Issue by CerenB** [cpp-lln-lab/CPP_BIDS_SPM_pipeline#90]
my not be working in matlab? 
Basically it does not create a copy of sub-001 folder into derivatives folder.

**Comment by Remi-Gau** [comment]
does the script `demo/batch_download_run.m` work?

`bidsCopyRawFolder(opt, 1);` is at line 89 on that one. Make sure it is not commented out.

**Comment by CerenB** [comment]
Hmm, not really. 
<img width="378" alt="Screenshot 2020-09-26 at 19 45 57" src="https://user-images.githubusercontent.com/10451654/94347014-0d366c00-0031-11eb-8873-845babfa5fe4.png">


```
derivatives directory created: /Users/battal/Documents/GitHub/CPPLab/CPP_BIDS_SPM_pipeline/demo/output/MoAEpilot/../derivatives/SPM12_CPPL 
K>> fullfile(rawDir, '*.json')

ans =

    '/Users/battal/Documents/GitHub/CPPLab/CPP_BIDS_SPM_pipeline/demo/output/MoAEpilot/*.json'

Error using copyfile
cp: /Users/battal/Documents/GitHub/CPPLab/CPP_BIDS_SPM_pipeline/demo/output/MoAEpilot/*.json: No
such file or directory

Error in bidsCopyRawFolder (line 44)
    copyfile(fullfile(rawDir, '*.json'), derivativeDir);

Error in batch_download_run (line 89)
bidsCopyRawFolder(opt, 1);
```

**Comment by Remi-Gau** [comment]
OK will have into this tomorrow

**Comment by Remi-Gau** [comment]
- [ ] create a test for `bidsCopyRawFolder`

**Comment by CerenB** [comment]
I usually initiate matlab from command + space but this problem persisted when I initiate it from terminal window as well. 
in `bidsCopyRawFolder.m ` in the section of:
```
try
        system( ...
          sprintf('cp -Lr %s %s', ...
          fullfile(rawDir, subDir), ...
          fullfile(derivativeDir, subDir)));
      catch
        message = [ ...
          'Copying data with system command failed: are you running Windows?\n', ...
          'Will use matlab/octave copyfile command instead.\n', ...
          'Could be an issue if your data set contains symbolic links' ...
          '(e.g. if you use datalad or git-annex.'];
        warning(message);
 
        copyfile(fullfile(rawDir, subDir), ...
          fullfile(derivativeDir, subDir));
      end
```
does not copy the subject folder. Without -L option, it works. with -Lr option it provides:
`cp: the -H, -L, and -P options may not be specified with the -r option.`

**Comment by marcobarilari** [comment]
I think we can close this one

**Comment by Remi-Gau** [comment]
@all-contributors please add @CerenB  for bug
