### ISSUE TITLE
rawDir and derivativesDir structuring

### ISSUE THREAD

**Issue by CerenB** [cpp-lln-lab/CPP_BIDS_SPM_pipeline#91]
I think in all the scripts, the derivatives and raw folder calling way is the same... 
but I made different structure for raw folder and derivatives. :D That's basically what Moh's repo in `dicom2BIDS` does. There is no raw folder. All the subjects folder etc. are inside 1 folder, including the derivatives

```
opt.dataDir ='/Users/battal/Cerens_files/fMRI/Processed/RhythmCateg/SequenceTestcopy/';
opt.jobsDir = fullfile( opt.dataDir,'derivatives', 'SPM12_CPPL', 'JOBS', opt.taskName);
```
Would we consider inserting `opt.dataDir` and `opt.DerivativesDir` into `getOptions.m` and the rest of the scripts would call it from the `opt.mat` file? 
Or I should change Moh's structuring? :)

**Comment by CerenB** [comment]
to be clear, I'm happy to make changes in my copy-only. And/or send a PR. (as a user I'm noting down the issues)

**Comment by Remi-Gau** [comment]
By default the pipeline is trying to follow the BIDS recommendations for derivatives:

https://bids-specification.readthedocs.io/en/stable/02-common-principles.html#storage-of-derived-datasets

This way MRIQC, fMRIprep, and CPP_SPM are all organized next to each other.

```
.
├── code
│   ├── analysis_high-res_localizers
│   └── bids_conversion
├── derivatives
│   ├── fmriprep
│   ├── mriqc
│   └── SPM12_CPPL
├── raw
│   ├── code
│   └── sub-pilot001
└── source
    └── sub-pilot001
```

You would like to be able to specify as a user where the derivatives should go? Is that right?

I can program that and actually I don't think we want the user to have to mention where the jobs should be saved: they should go in the same spot in the derivatives.

**Comment by Remi-Gau** [comment]
- [ ] allow user to decide where the derivatives will go (does not have to be a path relative to the raw dir)
- [ ] automate creation of the jobs directory

**Comment by Remi-Gau** [comment]
@CerenB 
you should now be able to set the derivatives wherever you want.
